FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY ["TTTT/TTTT.csproj", "TTTT/"]
RUN dotnet restore "TTTT/TTTT.csproj"
COPY . .
WORKDIR "/src/TTTT"
RUN dotnet build "TTTT.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "TTTT.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "TTTT.dll"]